"""added categories

Revision ID: e3888c4f5e04
Revises: 2e8c16f8c35a
Create Date: 2019-11-15 14:22:29.377297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3888c4f5e04'
down_revision = '2e8c16f8c35a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'category', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'category', type_='foreignkey')
    op.drop_column('category', 'user_id')
    # ### end Alembic commands ###
